"""
Threat models for VeriClip AI threat detection and tracking.
Tracks unauthorized usage of sports media across the internet.
"""

from datetime import datetime, timezone
from typing import Optional, List
from pydantic import BaseModel, Field


class ThreatCandidate(BaseModel):
    """
    A potential threat detected by the Scanner Agent.
    Requires verification before becoming a confirmed threat.
    """
    url: str = Field(min_length=5, description="URL of the potential infringement")
    title: str = Field(default="", description="Title or description of the content")
    snippet: str = Field(default="", description="Snippet or preview text")
    confidence: float = Field(ge=0.0, le=1.0, default=0.5, description="Initial confidence score")
    source: str = Field(description="Detection source: custom_search, telegram, youtube, etc.")
    detected_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    source_fingerprint_hash: Optional[str] = Field(default=None, description="Fingerprint hash of original media")


class ThreatEvent(BaseModel):
    """
    A confirmed threat after verification.
    Generated by the Alert Agent with evidence and takedown recommendation.
    """
    threat_id: str
    media_asset_id: str = Field(description="ID of the infringed media")
    infringement_url: str = Field(description="URL of the infringing content")
    infringement_title: str = Field(default="", description="Title of infringing content")
    threat_level: str = Field(description="Severity: low, medium, high, critical")
    confidence: float = Field(ge=0.0, le=1.0, description="Verified confidence")
    evidence_urls: List[str] = Field(default_factory=list, description="URLs to evidence screenshots/hashes")
    fingerprint_match_score: float = Field(default=0.0, description="Fingerprint similarity score")
    takedown_status: str = Field(default="pending", description="pending, submitted, completed, rejected")
    jurisdiction: Optional[str] = Field(default=None, description="Legal jurisdiction: IN, US, etc.")
    recipient: Optional[str] = Field(default=None, description="Platform or entity receiving the notice")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    verified_at: Optional[datetime] = Field(default=None)


class ThreatCandidateList(BaseModel):
    """List of threat candidates."""
    items: List[ThreatCandidate]
    total: int


class ThreatEventList(BaseModel):
    """List of confirmed threat events."""
    items: List[ThreatEvent]
    total: int


class TakedownNotice(BaseModel):
    """Generated takedown notice for a confirmed threat."""
    notice_id: str
    threat_id: str
    jurisdiction: str = Field(description="Legal jurisdiction: IN (Copyright Act 1957), US (DMCA)")
    notice_type: str = Field(description="dmca, copyright_act_1957, platform_report")
    recipient: str = Field(description="Platform or host receiving the notice")
    notice_content: str = Field(description="Full legal notice text")
    status: str = Field(default="draft", description="draft, sent, acknowledged, resolved")
    sent_at: Optional[datetime] = Field(default=None)
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
